export const calendarType = [
    { value: 'gregorian', label: 'Gregorian' },
  { value: 'hijri', label: 'Hijri' },
  { value: 'shamsi', label: 'Shamsi' },
  { value: 'bikram-sambat', label: 'Bikram Sambat' },
    
   
  ];
 
  export const countryList = [
    { label: 'Afghanistan', value: 'Afghanistan', currency: 'Afghan Afghani', currencyCode: 'AFN' },
    { label: 'Albania', value: 'Albania', currency: 'Albanian Lek', currencyCode: 'ALL' },
    { label: 'Algeria', value: 'Algeria', currency: 'Algerian Dinar', currencyCode: 'DZD' },
    { label: 'Andorra', value: 'Andorra', currency: 'Euro', currencyCode: 'EUR' },
    { label: 'Angola', value: 'Angola', currency: 'Angolan Kwanza', currencyCode: 'AOA' },
    { label: 'Antigua and Barbuda', value: 'Antigua and Barbuda', currency: 'East Caribbean Dollar', currencyCode: 'XCD' },
    { label: 'Argentina', value: 'Argentina', currency: 'Argentine Peso', currencyCode: 'ARS' },
    { label: 'Armenia', value: 'Armenia', currency: 'Armenian Dram', currencyCode: 'AMD' },
    { label: 'Australia', value: 'Australia', currency: 'Australian Dollar', currencyCode: 'AUD' },
    { label: 'Austria', value: 'Austria', currency: 'Euro', currencyCode: 'EUR' },
    { label: 'Azerbaijan', value: 'Azerbaijan', currency: 'Azerbaijani Manat', currencyCode: 'AZN' },
    { label: 'Bahamas', value: 'Bahamas', currency: 'Bahamian Dollar', currencyCode: 'BSD' },
    { label: 'Bahrain', value: 'Bahrain', currency: 'Bahraini Dinar', currencyCode: 'BHD' },
    { label: 'Bangladesh', value: 'Bangladesh', currency: 'Bangladeshi Taka', currencyCode: 'BDT' },
    { label: 'Barbados', value: 'Barbados', currency: 'Barbadian Dollar', currencyCode: 'BBD' },
    { label: 'Belarus', value: 'Belarus', currency: 'Belarusian Ruble', currencyCode: 'BYN' },
    { label: 'Belgium', value: 'Belgium', currency: 'Euro', currencyCode: 'EUR' },
    { label: 'Belize', value: 'Belize', currency: 'Belize Dollar', currencyCode: 'BZD' },
    { label: 'Benin', value: 'Benin', currency: 'West African CFA Franc', currencyCode: 'XOF' },
    { label: 'Bhutan', value: 'Bhutan', currency: 'Bhutanese Ngultrum', currencyCode: 'BTN' },
    { label: 'Bolivia', value: 'Bolivia', currency: 'Bolivian Boliviano', currencyCode: 'BOB' },
    { label: 'Bosnia and Herzegovina', value: 'Bosnia and Herzegovina', currency: 'Bosnia-Herzegovina Convertible Mark', currencyCode: 'BAM' },
    { label: 'Botswana', value: 'Botswana', currency: 'Botswana Pula', currencyCode: 'BWP' },
    { label: 'Brazil', value: 'Brazil', currency: 'Brazilian Real', currencyCode: 'BRL' },
    { label: 'Brunei', value: 'Brunei', currency: 'Brunei Dollar', currencyCode: 'BND' },
    { label: 'Bulgaria', value: 'Bulgaria', currency: 'Bulgarian Lev', currencyCode: 'BGN' },
    { label: 'Burkina Faso', value: 'Burkina Faso', currency: 'West African CFA Franc', currencyCode: 'XOF' },
    { label: 'Burundi', value: 'Burundi', currency: 'Burundian Franc', currencyCode: 'BIF' },
    { label: 'Cabo Verde', value: 'Cabo Verde', currency: 'Cape Verdean Escudo', currencyCode: 'CVE' },
    { label: 'Cambodia', value: 'Cambodia', currency: 'Cambodian Riel', currencyCode: 'KHR' },
    { label: 'Cameroon', value: 'Cameroon', currency: 'Central African CFA Franc', currencyCode: 'XAF' },
    { label: 'Canada', value: 'Canada', currency: 'Canadian Dollar', currencyCode: 'CAD' },
    { label: 'Central African Republic', value: 'Central African Republic', currency: 'Central African CFA Franc', currencyCode: 'XAF' },
    { label: 'Chad', value: 'Chad', currency: 'Central African CFA Franc', currencyCode: 'XAF' },
    { label: 'Chile', value: 'Chile', currency: 'Chilean Peso', currencyCode: 'CLP' },
    { label: 'China', value: 'China', currency: 'Chinese Yuan', currencyCode: 'CNY' },
    { label: 'Colombia', value: 'Colombia', currency: 'Colombian Peso', currencyCode: 'COP' },
    { label: 'Comoros', value: 'Comoros', currency: 'Comorian Franc', currencyCode: 'KMF' },
    { label: 'Congo, Democratic Republic of the', value: 'Congo, Democratic Republic of the', currency: 'Congolese Franc', currencyCode: 'CDF' },
    { label: 'Congo, Republic of the', value: 'Congo, Republic of the', currency: 'Central African CFA Franc', currencyCode: 'XAF' },
    { label: 'Costa Rica', value: 'Costa Rica', currency: 'Costa Rican Colón', currencyCode: 'CRC' },
    { label: 'Croatia', value: 'Croatia', currency: 'Croatian Kuna', currencyCode: 'HRK' },
    { label: 'Cuba', value: 'Cuba', currency: 'Cuban Peso', currencyCode: 'CUP' },
    { label: 'Cyprus', value: 'Cyprus', currency: 'Euro', currencyCode: 'EUR' },
    { label: 'Czech Republic', value: 'Czech Republic', currency: 'Czech Koruna', currencyCode: 'CZK' },
    { label: 'Denmark', value: 'Denmark', currency: 'Danish Krone', currencyCode: 'DKK' },
    { label: 'Djibouti', value: 'Djibouti', currency: 'Djiboutian Franc', currencyCode: 'DJF' },
    { label: 'Dominica', value: 'Dominica', currency: 'East Caribbean Dollar', currencyCode: 'XCD' },
    { label: 'Dominican Republic', value: 'Dominican Republic', currency: 'Dominican Peso', currencyCode: 'DOP' },
    { label: 'Ecuador', value: 'Ecuador', currency: 'United States Dollar', currencyCode: 'USD' },
    { label: 'Egypt', value: 'Egypt', currency: 'Egyptian Pound', currencyCode: 'EGP' },
    { label: 'El Salvador', value: 'El Salvador', currency: 'United States Dollar', currencyCode: 'USD' },
    { label: 'Equatorial Guinea', value: 'Equatorial Guinea', currency: 'Central African CFA Franc', currencyCode: 'XAF' },
    { label: 'Eritrea', value: 'Eritrea', currency: 'Eritrean Nakfa', currencyCode: 'ERN' },
    { label: 'Estonia', value: 'Estonia', currency: 'Euro', currencyCode: 'EUR' },
    { label: 'Eswatini', value: 'Eswatini', currency: 'Swazi Lilangeni', currencyCode: 'SZL' },
    { label: 'Ethiopia', value: 'Ethiopia', currency: 'Ethiopian Birr', currencyCode: 'ETB' },
    { label: 'Fiji', value: 'Fiji', currency: 'Fijian Dollar', currencyCode: 'FJD' },
    { label: 'Finland', value: 'Finland', currency: 'Euro', currencyCode: 'EUR' },
    { label: 'France', value: 'France', currency: 'Euro', currencyCode: 'EUR' },
    { label: 'Gabon', value: 'Gabon', currency: 'Central African CFA Franc', currencyCode: 'XAF' },
    { label: 'Gambia', value: 'Gambia', currency: 'Gambian Dalasi', currencyCode: 'GMD' },
    { label: 'Georgia', value: 'Georgia', currency: 'Georgian Lari', currencyCode: 'GEL' },
    { label: 'Germany', value: 'Germany', currency: 'Euro', currencyCode: 'EUR' },
    { label: 'Ghana', value: 'Ghana', currency: 'Ghanaian Cedi', currencyCode: 'GHS' },
    { label: 'Greece', value: 'Greece', currency: 'Euro', currencyCode: 'EUR' },
    { label: 'Grenada', value: 'Grenada', currency: 'East Caribbean Dollar', currencyCode: 'XCD' },
    { label: 'Guatemala', value: 'Guatemala', currency: 'Guatemalan Quetzal', currencyCode: 'GTQ' },
    { label: 'Guinea', value: 'Guinea', currency: 'Guinean Franc', currencyCode: 'GNF' },
    { label: 'Guinea-Bissau', value: 'Guinea-Bissau', currency: 'West African CFA Franc', currencyCode: 'XOF' },
    { label: 'Guyana', value: 'Guyana', currency: 'Guyanese Dollar', currencyCode: 'GYD' },
    { label: 'Haiti', value: 'Haiti', currency: 'Haitian Gourde', currencyCode: 'HTG' },
    { label: 'Honduras', value: 'Honduras', currency: 'Honduran Lempira', currencyCode: 'HNL' },
    { label: 'Hungary', value: 'Hungary', currency: 'Hungarian Forint', currencyCode: 'HUF' },
    { label: 'Iceland', value: 'Iceland', currency: 'Icelandic Króna', currencyCode: 'ISK' },
    { label: 'India', value: 'India', currency: 'Indian Rupee', currencyCode: 'INR' },
    { label: 'Indonesia', value: 'Indonesia', currency: 'Indonesian Rupiah', currencyCode: 'IDR' },
    { label: 'Iran', value: 'Iran', currency: 'Iranian Rial', currencyCode: 'IRR' },
    { label: 'Iraq', value: 'Iraq', currency: 'Iraqi Dinar', currencyCode: 'IQD' },
    { label: 'Ireland', value: 'Ireland', currency: 'Euro', currencyCode: 'EUR' },
    { label: 'Israel', value: 'Israel', currency: 'Israeli New Shekel', currencyCode: 'ILS' },
    { label: 'Italy', value: 'Italy', currency: 'Euro', currencyCode: 'EUR' },
    { label: 'Jamaica', value: 'Jamaica', currency: 'Jamaican Dollar', currencyCode: 'JMD' },
    { label: 'Japan', value: 'Japan', currency: 'Japanese Yen', currencyCode: 'JPY' },
    { label: 'Jordan', value: 'Jordan', currency: 'Jordanian Dinar', currencyCode: 'JOD' },
    { label: 'Kazakhstan', value: 'Kazakhstan', currency: 'Kazakhstani Tenge', currencyCode: 'KZT' },
    { label: 'Kenya', value: 'Kenya', currency: 'Kenyan Shilling', currencyCode: 'KES' },
    { label: 'Kiribati', value: 'Kiribati', currency: 'Australian Dollar', currencyCode: 'AUD' },
    { label: 'Korea, North', value: 'Korea, North', currency: 'North Korean Won', currencyCode: 'KPW' },
    { label: 'Korea, South', value: 'Korea, South', currency: 'South Korean Won', currencyCode: 'KRW' },
    { label: 'Kosovo', value: 'Kosovo', currency: 'Euro', currencyCode: 'EUR' },
    { label: 'Kuwait', value: 'Kuwait', currency: 'Kuwaiti Dinar', currencyCode: 'KWD' },
    { label: 'Kyrgyzstan', value: 'Kyrgyzstan', currency: 'Kyrgyzstani Som', currencyCode: 'KGS' },
    { label: 'Laos', value: 'Laos', currency: 'Lao Kip', currencyCode: 'LAK' },
    { label: 'Latvia', value: 'Latvia', currency: 'Euro', currencyCode: 'EUR' },
    { label: 'Lebanon', value: 'Lebanon', currency: 'Lebanese Pound', currencyCode: 'LBP' },
    { label: 'Lesotho', value: 'Lesotho', currency: 'Lesotho Loti', currencyCode: 'LSL' },
    { label: 'Liberia', value: 'Liberia', currency: 'Liberian Dollar', currencyCode: 'LRD' },
    { label: 'Libya', value: 'Libya', currency: 'Libyan Dinar', currencyCode: 'LYD' },
    { label: 'Liechtenstein', value: 'Liechtenstein', currency: 'Swiss Franc', currencyCode: 'CHF' },
    { label: 'Lithuania', value: 'Lithuania', currency: 'Euro', currencyCode: 'EUR' },
    { label: 'Luxembourg', value: 'Luxembourg', currency: 'Euro', currencyCode: 'EUR' },
    { label: 'Madagascar', value: 'Madagascar', currency: 'Malagasy Ariary', currencyCode: 'MGA' },
    { label: 'Malawi', value: 'Malawi', currency: 'Malawian Kwacha', currencyCode: 'MWK' },
    { label: 'Malaysia', value: 'Malaysia', currency: 'Malaysian Ringgit', currencyCode: 'MYR' },
    { label: 'Maldives', value: 'Maldives', currency: 'Maldivian Rufiyaa', currencyCode: 'MVR' },
    { label: 'Mali', value: 'Mali', currency: 'West African CFA Franc', currencyCode: 'XOF' },
    { label: 'Malta', value: 'Malta', currency: 'Euro', currencyCode: 'EUR' },
    { label: 'Marshall Islands', value: 'Marshall Islands', currency: 'United States Dollar', currencyCode: 'USD' },
    { label: 'Mauritania', value: 'Mauritania', currency: 'Mauritanian Ouguiya', currencyCode: 'MRU' },
    { label: 'Mauritius', value: 'Mauritius', currency: 'Mauritian Rupee', currencyCode: 'MUR' },
    { label: 'Mexico', value: 'Mexico', currency: 'Mexican Peso', currencyCode: 'MXN' },
    { label: 'Micronesia', value: 'Micronesia', currency: 'United States Dollar', currencyCode: 'USD' },
    { label: 'Moldova', value: 'Moldova', currency: 'Moldovan Leu', currencyCode: 'MDL' },
    { label: 'Monaco', value: 'Monaco', currency: 'Euro', currencyCode: 'EUR' },
    { label: 'Mongolia', value: 'Mongolia', currency: 'Mongolian Tögrög', currencyCode: 'MNT' },
    { label: 'Montenegro', value: 'Montenegro', currency: 'Euro', currencyCode: 'EUR' },
    { label: 'Morocco', value: 'Morocco', currency: 'Moroccan Dirham', currencyCode: 'MAD' },
    { label: 'Mozambique', value: 'Mozambique', currency: 'Mozambican Metical', currencyCode: 'MZN' },
    { label: 'Myanmar', value: 'Myanmar', currency: 'Burmese Kyat', currencyCode: 'MMK' },
    { label: 'Namibia', value: 'Namibia', currency: 'Namibian Dollar', currencyCode: 'NAD' },
    { label: 'Nauru', value: 'Nauru', currency: 'Australian Dollar', currencyCode: 'AUD' },
    { label: 'Nepal', value: 'Nepal', currency: 'Nepalese Rupee', currencyCode: 'NPR' },
    { label: 'Netherlands', value: 'Netherlands', currency: 'Euro', currencyCode: 'EUR' },
    { label: 'New Zealand', value: 'New Zealand', currency: 'New Zealand Dollar', currencyCode: 'NZD' },
    { label: 'Nicaragua', value: 'Nicaragua', currency: 'Nicaraguan Córdoba', currencyCode: 'NIO' },
    { label: 'Niger', value: 'Niger', currency: 'West African CFA Franc', currencyCode: 'XOF' },
    { label: 'Nigeria', value: 'Nigeria', currency: 'Nigerian Naira', currencyCode: 'NGN' },
    { label: 'North Macedonia', value: 'North Macedonia', currency: 'Macedonian Denar', currencyCode: 'MKD' },
    { label: 'Norway', value: 'Norway', currency: 'Norwegian Krone', currencyCode: 'NOK' },
    { label: 'Oman', value: 'Oman', currency: 'Omani Rial', currencyCode: 'OMR' },
    { label: 'Pakistan', value: 'Pakistan', currency: 'Pakistani Rupee', currencyCode: 'PKR' },
    { label: 'Palau', value: 'Palau', currency: 'United States Dollar', currencyCode: 'USD' },
    { label: 'Palestine', value: 'Palestine', currency: 'Israeli New Shekel', currencyCode: 'ILS' },
    { label: 'Panama', value: 'Panama', currency: 'Panamanian Balboa', currencyCode: 'PAB' },
    { label: 'Papua New Guinea', value: 'Papua New Guinea', currency: 'Papua New Guinean Kina', currencyCode: 'PGK' },
    { label: 'Paraguay', value: 'Paraguay', currency: 'Paraguayan Guaraní', currencyCode: 'PYG' },
    { label: 'Peru', value: 'Peru', currency: 'Peruvian Sol', currencyCode: 'PEN' },
    { label: 'Philippines', value: 'Philippines', currency: 'Philippine Peso', currencyCode: 'PHP' },
    { label: 'Poland', value: 'Poland', currency: 'Polish Złoty', currencyCode: 'PLN' },
    { label: 'Portugal', value: 'Portugal', currency: 'Euro', currencyCode: 'EUR' },
    { label: 'Qatar', value: 'Qatar', currency: 'Qatari Riyal', currencyCode: 'QAR' },
    { label: 'Romania', value: 'Romania', currency: 'Romanian Leu', currencyCode: 'RON' },
    { label: 'Russia', value: 'Russia', currency: 'Russian Ruble', currencyCode: 'RUB' },
    { label: 'Rwanda', value: 'Rwanda', currency: 'Rwandan Franc', currencyCode: 'RWF' },
    { label: 'Saint Kitts and Nevis', value: 'Saint Kitts and Nevis', currency: 'East Caribbean Dollar', currencyCode: 'XCD' },
    { label: 'Saint Lucia', value: 'Saint Lucia', currency: 'East Caribbean Dollar', currencyCode: 'XCD' },
    { label: 'Saint Vincent and the Grenadines', value: 'Saint Vincent and the Grenadines', currency: 'East Caribbean Dollar', currencyCode: 'XCD' },
    { label: 'Samoa', value: 'Samoa', currency: 'Samoan Tala', currencyCode: 'WST' },
    { label: 'San Marino', value: 'San Marino', currency: 'Euro', currencyCode: 'EUR' },
    { label: 'Sao Tome and Principe', value: 'Sao Tome and Principe', currency: 'São Tomé and Príncipe Dobra', currencyCode: 'STN' },
    { label: 'Saudi Arabia', value: 'Saudi Arabia', currency: 'Saudi Riyal', currencyCode: 'SAR' },
    { label: 'Senegal', value: 'Senegal', currency: 'West African CFA Franc', currencyCode: 'XOF' },
    { label: 'Serbia', value: 'Serbia', currency: 'Serbian Dinar', currencyCode: 'RSD' },
    { label: 'Seychelles', value: 'Seychelles', currency: 'Seychellois Rupee', currencyCode: 'SCR' },
    { label: 'Sierra Leone', value: 'Sierra Leone', currency: 'Sierra Leonean Leone', currencyCode: 'SLL' },
    { label: 'Singapore', value: 'Singapore', currency: 'Singapore Dollar', currencyCode: 'SGD' },
    { label: 'Slovakia', value: 'Slovakia', currency: 'Euro', currencyCode: 'EUR' },
    { label: 'Slovenia', value: 'Slovenia', currency: 'Euro', currencyCode: 'EUR' },
    { label: 'Solomon Islands', value: 'Solomon Islands', currency: 'Solomon Islands Dollar', currencyCode: 'SBD' },
    { label: 'Somalia', value: 'Somalia', currency: 'Somali Shilling', currencyCode: 'SOS' },
    { label: 'South Africa', value: 'South Africa', currency: 'South African Rand', currencyCode: 'ZAR' },
    { label: 'South Sudan', value: 'South Sudan', currency: 'South Sudanese Pound', currencyCode: 'SSP' },
    { label: 'Spain', value: 'Spain', currency: 'Euro', currencyCode: 'EUR' },
    { label: 'Sri Lanka', value: 'Sri Lanka', currency: 'Sri Lankan Rupee', currencyCode: 'LKR' },
    { label: 'Sudan', value: 'Sudan', currency: 'Sudanese Pound', currencyCode: 'SDG' },
    { label: 'Suriname', value: 'Suriname', currency: 'Surinamese Dollar', currencyCode: 'SRD' },
    { label: 'Sweden', value: 'Sweden', currency: 'Swedish Krona', currencyCode: 'SEK' },
    { label: 'Switzerland', value: 'Switzerland', currency: 'Swiss Franc', currencyCode: 'CHF' },
    { label: 'Syria', value: 'Syria', currency: 'Syrian Pound', currencyCode: 'SYP' },
    { label: 'Taiwan', value: 'Taiwan', currency: 'New Taiwan Dollar', currencyCode: 'TWD' },
    { label: 'Tajikistan', value: 'Tajikistan', currency: 'Tajikistani Somoni', currencyCode: 'TJS' },
    { label: 'Tanzania', value: 'Tanzania', currency: 'Tanzanian Shilling', currencyCode: 'TZS' },
    { label: 'Thailand', value: 'Thailand', currency: 'Thai Baht', currencyCode: 'THB' },
    { label: 'Timor-Leste', value: 'Timor-Leste', currency: 'United States Dollar', currencyCode: 'USD' },
    { label: 'Togo', value: 'Togo', currency: 'West African CFA Franc', currencyCode: 'XOF' },
    { label: 'Tonga', value: 'Tonga', currency: 'Tongan Paʻanga', currencyCode: 'TOP' },
    { label: 'Trinidad and Tobago', value: 'Trinidad and Tobago', currency: 'Trinidad and Tobago Dollar', currencyCode: 'TTD' },
    { label: 'Tunisia', value: 'Tunisia', currency: 'Tunisian Dinar', currencyCode: 'TND' },
    { label: 'Turkey', value: 'Turkey', currency: 'Turkish Lira', currencyCode: 'TRY' },
    { label: 'Turkmenistan', value: 'Turkmenistan', currency: 'Turkmenistani Manat', currencyCode: 'TMT' },
    { label: 'Tuvalu', value: 'Tuvalu', currency: 'Australian Dollar', currencyCode: 'AUD' },
    { label: 'Uganda', value: 'Uganda', currency: 'Ugandan Shilling', currencyCode: 'UGX' },
    { label: 'Ukraine', value: 'Ukraine', currency: 'Ukrainian Hryvnia', currencyCode: 'UAH' },
    { label: 'United Arab Emirates', value: 'United Arab Emirates', currency: 'United Arab Emirates Dirham', currencyCode: 'AED' },
    { label: 'United Kingdom', value: 'United Kingdom', currency: 'British Pound', currencyCode: 'GBP' },
    { label: 'United States', value: 'United States', currency: 'United States Dollar', currencyCode: 'USD' },
    { label: 'Uruguay', value: 'Uruguay', currency: 'Uruguayan Peso', currencyCode: 'UYU' },
    { label: 'Uzbekistan', value: 'Uzbekistan', currency: 'Uzbekistani Som', currencyCode: 'UZS' },
    { label: 'Vanuatu', value: 'Vanuatu', currency: 'Vanuatu Vatu', currencyCode: 'VUV' },
    { label: 'Vatican City', value: 'Vatican City', currency: 'Euro', currencyCode: 'EUR' },
    { label: 'Venezuela', value: 'Venezuela', currency: 'Venezuelan Bolívar', currencyCode: 'VES' },
    { label: 'Vietnam', value: 'Vietnam', currency: 'Vietnamese Dong', currencyCode: 'VND' },
    { label: 'Yemen', value: 'Yemen', currency: 'Yemeni Rial', currencyCode: 'YER' },
    { label: 'Zambia', value: 'Zambia', currency: 'Zambian Kwacha', currencyCode: 'ZMW' },
    { label: 'Zimbabwe', value: 'Zimbabwe', currency: 'Zimbabwean Dollar', currencyCode: 'ZWL' },
  ];

export const languagesList1 = [
  { label: 'English', value: 'English'},
  { label: 'Arabic', value: 'Arabic'},
  { label: 'Persian', value: 'Persian'},
  { label: 'Chinese', value: 'Chinese'},
  { label: 'Spanish', value: 'Spanish'},
  { label: 'Portuguese', value: 'Portuguese'},
  { label: 'Indonesian', value: 'Indonesian'},
  { label: 'Alt English', value: 'Alt English'},


]  
export const companyList = [
  { value: 'Company1', label: 'Company1' },
{ value: 'Company2', label: 'Company2' },

  
 
];
  
  