
export const imageIcon = "/images/sangsolution.png";
export const primaryColor = "#00405E"
export const secondryColor = "#1E8FD8"
export const thirdColor = "#0073AA"
export const primaryButtonColor = "#ffff"
export const activePrimaryColor = "#1D4D86"

export const SideBarIcons = [
  { id: 1, parent: 0, iconName: "Home", icon: import("@mui/icons-material/Home"), child: true },
  { id: 2, parent: 0, iconName: "Financials", icon: import("@mui/icons-material/LocalAtm"), child: true },
  { id: 3, parent: 0, iconName: "Inventory", icon: import("@mui/icons-material/Inventory"), child: false },
  { id: 4, parent: 0, iconName: "Fixed Asset", icon: import("@mui/icons-material/AccountBalance"), child: false },
  { id: 5, parent: 0, iconName: "Production", icon: import("@mui/icons-material/Warehouse"), child: false },
  { id: 6, parent: 0, iconName: "Point of Sale", icon: import("@mui/icons-material/PointOfSale"), child: false },
  { id: 7, parent: 0, iconName: "Quality Control", icon: import("@mui/icons-material/PlaylistAddCheck"), child: false },
  { id: 8, parent: 0, iconName: "Settings", icon: import("@mui/icons-material/Settings"), child: true },
  { id: 9, parent: 1, iconName: "Company", icon: null, child: true },
  { id: 10, parent: 1, iconName: "Security", icon: null, child: true },
  { id: 11, parent: 1, iconName: "Tag", icon: null, child: true },
  { id: 12, parent: 10, iconName: "Create Profile", icon: null, url: "/security" },
  { id: 13, parent: 10, iconName: "Create Role", icon: null, url: "/security" },
  { id: 14, parent: 10, iconName: "Create User", icon: null, url: "/security" },
  { id: 15, parent: 11, iconName: "Account", icon: null, child: true },
  // { id: 16, parent: 11, iconName: "Currency", icon: null, url: "/Master"},
  { id: 17, parent: 11, iconName: "Product", icon: null, child: true },
  { id: 16, parent: 11, iconName: "Currency", icon: null,child: true},
  { id: 18, parent: 11, iconName: "Warehouse", icon: null, url: "/Master" },
  { id: 19, parent: 15, iconName: "Account Tag", icon: null, url: "/Master" },
  { id: 20, parent: 15, iconName: "Customer/Vendor Tag", icon: null, url: "/Master" },
  { id: 21, parent: 38, iconName: "Currency Tag", icon: null, url: "/EntitySettings" },
  // { id: 22, parent: 38, iconName: "Exchange Rate", icon: null, url: "/EntitySettings" },
  // { id: 23, parent: 38, iconName: "Exchange Rate History", icon: null, url: "/EntitySettings" },
  { id: 24, parent: 17, iconName: "Product", icon: null, url: "/Master" },
  { id: 25, parent: 17, iconName: "Unit", icon: null, url: "/Master" },
  { id: 26, parent: 17, iconName: "Unit Conversion", icon: null, url: "/Master" },
  { id: 27, parent: 17, iconName: "Seller Price Book", icon: null, url: "/Master" },
  { id: 28, parent: 17, iconName: "Buyer Price Book", icon: null, url: "/Master" },
  { id: 29, parent:17, iconName: "Barcode Definition", icon:  import("@mui/icons-material/Inventory"),url:"/Master" },
  { id: 30, parent: 8, iconName: "General Settings", icon: null, url: "/GeneralSettings" },
  // { id: 32, parent: 8, iconName: "Master Settings", icon: null, url: "/MasterSettings" },
  { id: 31, parent: 8, iconName: "Voucher Settings", icon: null, child:true },

  { id: 33,parent:8, iconName: "Tag Settings", icon:  null ,url:"/TagCreation" },
  // { id: 34, parent:30, iconName: "Account tag Management", icon:  import("@mui/icons-material/Inventory"),url:"/MainSettings" },
  { id: 35, parent: 9, iconName: "Open Company", icon: null, url: "/OpenCompany" },
  // { id: 36, parent:9, iconName: "Create Company", icon:  import("@mui/icons-material/Home"),url:"/Company" },
  { id: 37, parent: 9, iconName: "Edit Company", icon: null, url: "/Company" },
  { id: 38, parent: 39, iconName: "Currency", icon: null, child: true  },
  // { id: 39, parent: 8, iconName: "Entity Settings", icon: null, child: true },
  { id: 40, parent: 39, iconName: "Finance", icon: null, url: "/EntitySettings" },
  { id: 41, parent: 39, iconName: "Inventory", icon: null, url: "/EntitySettings" },
  { id: 42, parent: 39, iconName: "Fixed Asset", icon: null, url: "/EntitySettings" },
  { id: 43, parent: 39, iconName: "General", icon: null, url: "/EntitySettings" },
  { id: 44, parent: 8, iconName: "Configuration", icon: null, child: true },
  { id: 45, parent: 44, iconName: "Voucher Configuration", icon: null, url: "/Configuration" },
  { id: 46, parent: 44, iconName: "Tag Configuration", icon: null, url: "/Configuration" },
  { id: 47, parent: 44, iconName: "Views Configuration", icon: null, url: "/Configuration" },
  { id: 48, parent: 44, iconName: "Work Flow", icon: null, url: "/Configuration" },
  { id: 49, parent: 44, iconName: "VAT Configuration", icon: null, url: "/Configuration" },
  { id: 50, parent: 8, iconName: "Business Entity", icon: null, url: "/EntityMaster" },
  { id: 51, parent: 11, iconName: "Fixed Asset", icon: null, url: "/Master" },
  { id: 52, parent: 11, iconName: "Tax Code", icon: null, url: "/Master" },
  { id: 53, parent: 11, iconName: "Place of Supply", icon: null, url: "/Master" },
  { id: 54, parent: 11, iconName: "Jurisdiction", icon: null, url: "/Master" },
  { id: 55, parent: 11, iconName: "Bank", icon: null, url: "/Master" },
  { id: 56, parent: 11, iconName: "Bank Branches", icon: null, url: "/Master" },
  { id: 57, parent: 11, iconName: "Outlet", icon: null, url: "/Master" },
  { id: 58, parent: 11, iconName: "Nationality", icon: null, url: "/Master" },
  { id: 59, parent: 11, iconName: "Country", icon: null, url: "/Master" },
  { id: 60, parent: 11, iconName: "Province", icon: null, url: "/Master" },
  { id: 61, parent: 11, iconName: "Territory", icon: null, url: "/Master" },
  { id: 62, parent: 11, iconName: "Township", icon: null, url: "/Master" },
  { id: 63, parent: 11, iconName: "Zone", icon: null, url: "/Master" },
  { id: 64, parent: 11, iconName: "City", icon: null, url: "/Master" },
  { id: 65, parent: 11, iconName: "Employee", icon: null, url: "/Master" },
  { id: 66, parent: 8, iconName: "View", icon: null, child: true },
  { id: 67, parent: 11, iconName: "Account Type", icon: null, url: "/Master" },
  { id: 68, parent: 11, iconName: "Employee Category", icon: null, url: "/Master" },
  { id: 69, parent: 11, iconName: "Bin", icon: null, url: "/Master" },
  { id: 70, parent: 10, iconName: "Password Policy", icon: null, url: "/security" },
  { id: 71, parent: 10, iconName: "Change Password", icon: null, url: "/security" },
  { id: 72, parent: 10, iconName: "Update Personal Info", icon: null, url: "/security" },
  { id: 73, parent: 31, iconName: "Request", icon: null, url: "/VoucherSettings" },
  { id: 74, parent: 31, iconName: "Order", icon: null, url: "/VoucherSettings" },
  { id: 75, parent: 31, iconName: "Receipt/Payment", icon: null, url: "/VoucherSettings" },
  { id: 76, parent: 31, iconName: "Invoice", icon: null, url: "/VoucherSettings" },
  { id: 77, parent: 31, iconName: "Journal", icon: null, url: "/VoucherSettings" },
  { id: 78, parent: 2, iconName: "Sales", icon: null, url: "/Sales" },
  { id: 79, parent: 16, iconName: "Currency Tag", icon: null, url: "/Master"},
  { id: 80, parent: 16, iconName: "Exchange Rate", icon: null, url: "/Master"},
  { id: 81, parent: 16, iconName: "Exchange Rate History", icon: null, url: "/Master"},
  { id: 82, parent: 66, iconName: "Tag View", icon: null, url: "/View"},
  { id: 83, parent: 66, iconName: "Transaction View", icon: null, url: "/View"},
];


export const EntityFieldData = [
  {
    icon: "",
    Entity: "Product",
    Account1Dependency: "Revenue",
    Account2Dependency: "Expense",
    ItemDependency: "Inventory",
    DefaultAccount1: "Sales Account",
    DefaultAccount2: "COGS Account",
    EntityRestrictCondition: "Stock > 0",
    EntityRestrictMessage: "Stock must be available.",
    Account1: "Account-A",
    Account2: "Account-B",
    AllowEntry: "Yes",
    CostOfIssueAccount: "COI-A",
    SalesPurchaseAc: "Sales-1",
  },
  {
    icon: "",
    Entity: "Service",
    Account1Dependency: "Income",
    Account2Dependency: "Liability",
    ItemDependency: "N/A",
    DefaultAccount1: "Service Revenue",
    DefaultAccount2: "Prepaid Revenue",
    EntityRestrictCondition: "Agreement Signed",
    EntityRestrictMessage: "Contract required.",
    Account1: "Account-C",
    Account2: "Account-D",
    AllowEntry: "No",
    CostOfIssueAccount: "N/A",
    SalesPurchaseAc: "Service-1",
  },
  {
    icon: "",
    Entity: "Material",
    Account1Dependency: "Raw Materials",
    Account2Dependency: "Supplies",
    ItemDependency: "Warehouse",
    DefaultAccount1: "Material Account",
    DefaultAccount2: "Supplies Account",
    EntityRestrictCondition: "In Stock",
    EntityRestrictMessage: "Material must be in stock.",
    Account1: "Account-E",
    Account2: "Account-F",
    AllowEntry: "Yes",
    CostOfIssueAccount: "COI-B",
    SalesPurchaseAc: "Purchase-1",
  },
  {
    icon: "",
    Entity: "Asset",
    Account1Dependency: "Depreciation",
    Account2Dependency: "Amortization",
    ItemDependency: "Fixed Assets",
    DefaultAccount1: "Depreciation Account",
    DefaultAccount2: "Accumulated Depreciation",
    EntityRestrictCondition: "Asset Registered",
    EntityRestrictMessage: "Asset needs registration.",
    Account1: "Account-G",
    Account2: "Account-H",
    AllowEntry: "Yes",
    CostOfIssueAccount: "COI-C",
    SalesPurchaseAc: "Asset-1",
  },
  {
    icon: "",
    Entity: "Employee",
    Account1Dependency: "Salary",
    Account2Dependency: "Benefits",
    ItemDependency: "Payroll",
    DefaultAccount1: "Wages Account",
    DefaultAccount2: "Benefits Account",
    EntityRestrictCondition: "Active Status",
    EntityRestrictMessage: "Employee must be active.",
    Account1: "Account-I",
    Account2: "Account-J",
    AllowEntry: "No",
    CostOfIssueAccount: "N/A",
    SalesPurchaseAc: "Payroll-1",
  },
  {
    icon: "",
    Entity: "Vendor",
    Account1Dependency: "Payables",
    Account2Dependency: "Expenses",
    ItemDependency: "N/A",
    DefaultAccount1: "Vendor Payable",
    DefaultAccount2: "Operating Expense",
    EntityRestrictCondition: "Valid Vendor ID",
    EntityRestrictMessage: "Vendor must be verified.",
    Account1: "Account-K",
    Account2: "Account-L",
    AllowEntry: "Yes",
    CostOfIssueAccount: "N/A",
    SalesPurchaseAc: "Vendor-1",
  },
  {
    icon: "",
    Entity: "Customer",
    Account1Dependency: "Receivables",
    Account2Dependency: "Revenue",
    ItemDependency: "N/A",
    DefaultAccount1: "Customer Receivable",
    DefaultAccount2: "Sales Revenue",
    EntityRestrictCondition: "Credit Limit OK",
    EntityRestrictMessage: "Credit limit exceeded.",
    Account1: "Account-M",
    Account2: "Account-N",
    AllowEntry: "No",
    CostOfIssueAccount: "N/A",
    SalesPurchaseAc: "Customer-1",
  },
  {
    icon: "",
    Entity: "Contract",
    Account1Dependency: "Prepaid Revenue",
    Account2Dependency: "Liabilities",
    ItemDependency: "N/A",
    DefaultAccount1: "Contract Revenue",
    DefaultAccount2: "Unearned Revenue",
    EntityRestrictCondition: "Contract Signed",
    EntityRestrictMessage: "Valid contract required.",
    Account1: "Account-O",
    Account2: "Account-P",
    AllowEntry: "Yes",
    CostOfIssueAccount: "COI-D",
    SalesPurchaseAc: "Contract-1",
  },
  {
    icon: "",
    Entity: "Project",
    Account1Dependency: "Budget",
    Account2Dependency: "Expenses",
    ItemDependency: "Resources",
    DefaultAccount1: "Project Budget",
    DefaultAccount2: "Project Expense",
    EntityRestrictCondition: "Budget Approved",
    EntityRestrictMessage: "Budget approval needed.",
    Account1: "Account-Q",
    Account2: "Account-R",
    AllowEntry: "Yes",
    CostOfIssueAccount: "COI-E",
    SalesPurchaseAc: "Project-1",
  },
  {
    icon: "",
    Entity: "Inventory",
    Account1Dependency: "Stock",
    Account2Dependency: "Reorder",
    ItemDependency: "Warehouse",
    DefaultAccount1: "Stock Account",
    DefaultAccount2: "Reorder Account",
    EntityRestrictCondition: "Sufficient Quantity",
    EntityRestrictMessage: "Insufficient stock.",
    Account1: "Account-S",
    Account2: "Account-T",
    AllowEntry: "No",
    CostOfIssueAccount: "COI-F",
    SalesPurchaseAc: "Inventory-1",
  },
];
